Home work
AnastasiiaYan/TeachMeSkills pull request #1
Opened 2023-12-05 11:24 UTC by AnastasiiaYan

Выполнены задания по теме TypesAndOperators (4 задачи), LoopsAndArrays (4 задачи), и частично CharAndStrings (3 задачи)

2023-12-09 13:22 UTC, AnastasiiaYan commented
Завершены задачи для темы CharAndStrings

2023-12-11 13:40 UTC, wildpioneer requested changes

2023-12-11 13:40 UTC, wildpioneer commented on TypesAndOperators/HomeWork_1.cs
> +            switch (operand)
Форматирование:
1. Логические блоки делим пустыми строками
2. Перед for, switch, if - ставим пустую строку

2023-12-11 13:40 UTC, wildpioneer commented on TypesAndOperators/HomeWork_3.cs
> +
Лишняя пустая строка

2023-12-11 13:40 UTC, wildpioneer commented on TypesAndOperators/HomeWork_4.cs
> +        public static void IsEven() //первый вариант решения задачи с if/else
Пустая строка перед методом

2023-12-11 13:40 UTC, wildpioneer commented on LoopsAndArrays/HomeWork_2.cs
> +                while (Array.Exists(numbers, element => element == input))
Конечно круто сделано - однако к этому моменту мы не знаем таких конструкций.

2023-12-11 13:40 UTC, wildpioneer commented on LoopsAndArrays/HomeWork_3.cs
> +            Console.WriteLine($"Минимальное число массива - {arrayСontent.Min()}");
А где среднее число?

2023-12-11 13:40 UTC, wildpioneer commented on LoopsAndArrays/HomeWork_4.cs
> +            else if (firstarray.Average() == secondarray.Average())
Это условие уже излишнее - потому как кроме третьего случая ничего быть не может ;)

2023-12-11 13:40 UTC, wildpioneer commented on MethodsAndClasses/HomeWork_1.cs
> +            Phone phone1 = new Phone();
Эту работу надо вынесли в отдельный бранч и сделать PR на Геннадия

2023-12-11 13:40 UTC, wildpioneer commented on CharAndStrings/HomeWork_4.cs
> +/*Substring принимает 2 аргумента : начальный индекс и количество символов, которые нужно удалить.
Ненужный закомментированный код не оставляем в PR

2023-12-26 08:55 UTC, wildpioneer commented
Здесь ждать исправлений или можно закрывать?

2024-01-13 22:05 UTC, AnastasiiaYan commented on TypesAndOperators/HomeWork_3.cs
> +
Удалена лишняя строка в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]

2024-01-13 22:05 UTC, AnastasiiaYan commented on TypesAndOperators/HomeWork_4.cs
> +        public static void IsEven() //первый вариант решения задачи с if/else
Добавлена пустая строка в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]

2024-01-13 22:05 UTC, AnastasiiaYan commented on LoopsAndArrays/HomeWork_3.cs
> +            Console.WriteLine($"Минимальное число массива - {arrayСontent.Min()}");
Добавила в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]
Console.WriteLine($"Среднее число массива - {arrayСontent.Average()}");

2024-01-13 22:06 UTC, AnastasiiaYan commented on LoopsAndArrays/HomeWork_4.cs
> +            else if (firstarray.Average() == secondarray.Average())
Удален блок в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]

2024-01-13 22:06 UTC, AnastasiiaYan commented on MethodsAndClasses/HomeWork_1.cs
> +            Phone phone1 = new Phone();
Спасибо, в данном pull request прошу принять на проверку задания по темам:
Основы типов и операторы - TypesAndOperators (4 задачи),
Циклы и массивы - LoopsAndArrays (4 задачи),
Символы и строки - CharAndStrings (4 задачи).

Задачи по темам, начиная с "Методы и Классы" будут оформляться в отдельные бранчи.

2024-01-13 22:06 UTC, AnastasiiaYan commented on CharAndStrings/HomeWork_4.cs
> +/*Substring принимает 2 аргумента : начальный индекс и количество символов, которые нужно удалить.
Удален блок в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]

2024-01-13 22:07 UTC, AnastasiiaYan commented
В данном pull request прошу принять на проверку задания по темам:
Основы типов и операторы - TypesAndOperators (4 задачи),
Циклы и массивы - LoopsAndArrays (4 задачи),
Символы и строки - CharAndStrings (4 задачи).

Задачи по темам, начиная с "Методы и Классы" будут оформляться в отдельные бранчи и соответственно отдельные ull request

2024-01-14 09:01 UTC, AnastasiiaYan commented on TypesAndOperators/HomeWork_1.cs
> +            switch (operand)
Добавлена строка в Commit: 1ac776678907a730bd194dfbf3bb310caa1feb11 [1ac7766]

2024-01-29 09:34 UTC, wildpioneer commented
Проверено

2024-01-29 09:34 UTC, closed without merging